# Generated by Django 4.0.4 on 2022-05-30 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumb_cursos')),
                ('descicao', models.TextField(max_length=10000)),
                ('categoria', models.CharField(choices=[('FRONT-END', 'FRONT-END'), ('BACK-END', 'BACK_END'), ('GITHUB', 'GIT - GITHUB'), ('BANCO_DE_DADOS', 'BANCO DE DADOS'), ('OUTROS', 'OUTROS'), ('INGLES', 'INGLÊS')], max_length=25)),
                ('vizualizacao', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
