# Generated by Django 4.0.4 on 2022-06-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='descicao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='vizualizacao',
            new_name='visualizacao',
        ),
    ]
