# Generated by Django 4.0.4 on 2022-06-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cursos_vistos',
            field=models.ManyToManyField(to='home.curso'),
        ),
    ]
